### ISSUE TITLE
Does not work for me :(

### ISSUE THREAD

**Issue by mitya12342** [Lichtso/hair_guides#1]
```
Traceback (most recent call last):
  File "C:\Users\Mitya\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\hair_guides-blender280\__init__.py", line 184, in execute
    vertex = pasy.particles[hair_index].hair_keys[step_index]
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

location: <unknown location>:-1
```
Am i doing anything wrong? Fires after execution from search. Did everything according readme.
```
>>> bpy.app
bpy.app(version=(2, 80, 74), version_string='2.80 (sub 74)', version_char='', version_cycle='beta', binary_path='D:\\blender-2.80.0-git.e7a0f0a9934e-windows64\\blender.exe', background=False, factory_startup=False, build_date=b'22/06/2019', build_time=b'17:53', build_commit_timestamp=1561247845, build_commit_date=b'2019-06-22', build_commit_time=b'23:57', build_hash=b'e7a0f0a9934e', build_branch=b'master', build_platform=b'Windows', build_type=b'Release', ...)
```

**Comment by Lichtso** [comment]
Blender 2.80 still has lots of bugs when it comes to particle hair.
Thus the add-on won't work yet, even though there is already a development branch for the new blender version.

You can stay up to date here:
https://blenderartists.org/t/particle-hair-from-meshes-bezier-curves-nurbs/1154670/7

**Comment by Lichtso** [comment]
As Blender 2.80 is now released I went back to this add-on again and got it running.
You can download it from this branch: https://github.com/Lichtso/hair_guides/tree/blender280
