### ISSUE TITLE
I added Panel to addon, it works on 2.82 but in 2.83 Alpha Blender crash.

### ISSUE THREAD

**Issue by Oxervision** [Lichtso/hair_guides#3]
Hi, thanks for the addon!!

I added a Panel to the addon, and I placed in Sidebar > Create Tab, the addon works fine in 2.82a release but in 2.83 Alpha when you push the 'Particle Hair from Guides' button, Blender crash, I suppose that they have made changes in API.

This is the addon with Panel:

[hair_guides 2.80 Panel.zip](https://github.com/Lichtso/hair_guides/files/4383182/hair_guides.2.80.Panel.zip)

**Comment by Lichtso** [comment]
Fixed: https://developer.blender.org/T76131
