### ISSUE TITLE
Can we have it so it doesnt delete the original mesh, just hides it?

### ISSUE THREAD

**Issue by slayermaster** [Lichtso/hair_guides#6]
I tried this addon and it works great. Just that when I changed my mind on the hair, i cannot reuse the old mesh. Can you make it so the mesh is still usable after running this?

**Comment by Michaelwhite34** [comment]
The mesh is just disabled in viewport after running the script,you can enable it again.

**Comment by Lichtso** [comment]
As @Michaelwhite34 said, this is already the case.
